name: at_file_share
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  at_onboarding_cli : ^1.4.3
  http: ^1.0.0
  at_client: ^3.0.75
  at_chops: ^2.0.0
  at_cli_commons: ^1.0.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
