name: at_data_share
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.4.1
  at_client: ^3.0.61
  at_utils: ^3.0.12

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
