name: iot_sender
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

dependencies:
  max30101: ^1.0.0-RC
  at_utils: ^3.0.5
  at_client: ^3.0.12
  image: ^3.1.1
  mqtt_client: ^9.6.5
  zxing2: ^0.1.0
  at_onboarding_cli: ^1.1.1

dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      ref: ignore_offline_notifications
      path: at_client
