name: sshnp_docker_demo_base
on:
  schedule:
    - cron: '35 11 * * 5' # 11 35 on friday
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          file: sshnp_docker_demo/demo-base/Dockerfile
          push: true
          tags: |
            atsigncompany/sshnp_docker_demo_base:latest
            atsigncompany/sshnp_docker_demo_base:GHA${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
