name: sshnp_docker_demo_base
on:
  schedule:
    - cron: '35 11 * * 5' # 11 35 on friday
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0

      - name: Login to DockerHub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          file: sshnp_docker_demo/demo-base/Dockerfile
          push: true
          tags: |
            atsigncompany/sshnp_docker_demo_base:latest
            atsigncompany/sshnp_docker_demo_base:GHA${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
